[package]
name = "mcp-sse"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
shuttle-runtime = "0.56.0"
tokio = { version = "1", features = ["macros", "rt-multi-thread", "signal"] }
rmcp = { version = "0.3", features = ["server", "transport-sse-server"] }
axum = "0.8"
anyhow = "1.0"
tracing = "0.1"
tokio-util = "0.7"
