[workspace]

[package]
name = "loco_starter_template"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
shuttle-axum = "0.39.0"
shuttle-metadata = "0.39.0"
shuttle-runtime = { version = "0.39.0", default-features = false }
shuttle-shared-db = { version = "0.39.0", features = ["postgres"] }
loco-rs = { version = "0.3.1", features = ["auth_jwt"] }
migration = { path = "migration" }

serde = { version = "1", features = ["derive"] }
serde_json = "1"
eyre = "0.6"
tokio = { version = "1.33.0", default-features = false }
async-trait = "0.1.74"
tracing = "0.1.40"
chrono = "0.4"
validator = { version = "0.16" }
sea-orm = { version = "1.0.0-rc.1", features = [
  "sqlx-sqlite",
  "sqlx-postgres",
  "runtime-tokio-rustls",
  "macros",
] }
axum = { version = "0.7.1", features = ["macros"] }
include_dir = "0.7"
uuid = { version = "1.6.0", features = ["v4"] }
tracing-subscriber = { version = "0.3.17", features = ["env-filter", "json"] }

# view engine i18n
fluent-templates = { version = "0.8.0", features = ["tera"] }
unic-langid = "0.9.4"
async-stripe = { version = "0.34.1", features = ["runtime-tokio-hyper-rustls"] }
thiserror = "1.0.57"
shuttle-secrets = "0.39.0"
# /view engine

[[bin]]
name = "loco_starter_template-cli"
path = "src/bin/main.rs"
required-features = []

[[bin]]
name = "loco_starter_template"
path = "src/bin/shuttle.rs"

[dev-dependencies]
serial_test = "2.0.0"
rstest = "0.18.2"
loco-rs = { version = "0.3.1", features = ["testing"] }
insta = { version = "1.34.0", features = ["redactions", "yaml", "filters"] }
