[package]
name = "mcp-sse-oauth"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
schemars = { version = "1" }
shuttle-runtime = "0.56.0"
shuttle-shared-db = { version = "0.56.0", features = ["postgres", "sqlx"] }
tokio = { version = "1", features = ["macros", "rt-multi-thread", "signal"] }
rmcp = { version = "0.5", features = [
  "server",
  "transport-sse-server",
  "auth",
] }
axum = "0.8"
anyhow = "1.0"
tracing = "0.1"
tokio-util = "0.7"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tower-http = { version = "0.6.6", features = ["cors"] }
sqlx = { version = "0.8.2", features = [
  "runtime-tokio-rustls",
  "postgres",
  "chrono",
  "uuid",
] }
uuid = { version = "1.17", features = ["v4", "serde"] }
rand = "0.9"
chrono = { version = "0.4", features = ["serde"] }
askama = "0.14"
jsonwebtoken = "9.3"
sha2 = "0.10"
base64 = "0.22"
